#!/bin/sh
#
# Copyright (c) 2014 Citrix Systems, Inc.
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
# 
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#

DOMID=$1
shift 2

# configure and use per-vm alsa pcm device with softvol control
ALSA_VMID=$DOMID

# config files
ASOUND_CONF=/etc/asound.conf
ASOUND_CONF_VMID=/var/run/alsa-vm-${ALSA_VMID}.conf

cat > ${ASOUND_CONF_VMID} <<END
pcm.vm-${ALSA_VMID} {
  type softvol
  slave {
    pcm "asym0"
  }
  control {
    name "vm-${ALSA_VMID}"
    card 0
  }
}
END

cat ${ASOUND_CONF} >> ${ASOUND_CONF_VMID}
export ALSA_CONFIG_PATH=/usr/share/alsa/alsa.conf:${ASOUND_CONF_VMID}
export QEMU_ALSA_DAC_DEV=plug:vm-${ALSA_VMID}
export QEMU_ALSA_ADC_DEV=plug:dsnoop0
export QEMU_ALSA_VOL_CTRL=vm-${ALSA_VMID}

name="qemu-$DOMID"

ARGS="$*"

logger -t $name "Using domid: $DOMID"
logger -t $name "Arguments: $ARGS"

export USE_INTEL_SB=1
export INTEL_DBUS=1
exec /usr/lib/xen/bin/qemu-dm -name qemu-$DOMID $ARGS
